package uk.ac.dotrural.prov;

import java.util.Collection;

public interface ProvenanceGetter {
	/**
	 * Gets the URI of agents agent with URI agentURI has acted on behalf of
	 * 
	 * @param agentUri
	 *            URI of Agent resource that acted on behalf of another agent(s)
	 * @return URIs of Agents that agentUri has acted on behalf of
	 */
	public Collection<String> getActedOnBehalfOf(String agentUri);

	/**
	 * Gets the timestamp for when an Activity ended
	 * 
	 * @param activityUri
	 *            URI of Activity resource
	 * @return The dateTime timestamp that the activity ended
	 */
	public long getEndedAtTime(String activityUri);

	/**
	 * Gets the timestamp for when an Activity started
	 * 
	 * @param activityUri
	 *            URI of Activity resource
	 * @return The dateTime timestamp the activity started
	 */
	public long getStartedAtTime(String activityUri);

	/**
	 * Gets the URI of Entities used by the Activity with URI activityUri
	 * 
	 * @param activityUri
	 *            URI of Activity resource
	 * @return URIs of Entities resources used by the activity
	 */
	public Collection<String> getUsed(String activityUri);

	/**
	 * Gets the URI of Agents associated with the Activity with URI activityUri
	 * 
	 * @param activityUri
	 *            URI of Activity resource
	 * @return URIs of Agents associated with the Activity
	 */
	public Collection<String> getWasAssociatedWith(String activityUri);

	/**
	 * Gets the URI of Agents the Entity with URI entityUri was attributed to
	 * 
	 * @param entityUri
	 *            URI of Entity resource
	 * @return URIs of Agents the Entity with URI entityUri was attributed to
	 */
	public Collection<String> getWasAttributedTo(String entityUri);

	/**
	 * Gets the URI of Entities that with URI entityUri was derived from
	 * 
	 * @return URIs of Entities the Entity with URI entityUri was derived from
	 *         to
	 */
	public Collection<String> getWasDerivedFrom(String entityUri);

	/**
	 * Gets the URIs of Activities that the Entity with URI entityUri was
	 * generated by
	 * 
	 * 
	 * @param entityUri
	 *            URI of Entity resource
	 * @return URIs of Activities the Entity with URI entityUri was generated by
	 * 
	 */
	public Collection<String> getWasGeneratedBy(String entityUri);

	/**
	 * Gets the URIs of Activities that Activity with URI activityUri was
	 * informed by
	 * 
	 * @param activityUri
	 *            URI of Activity resource
	 * @return URIs of Activities the Entity with URI entityUri was informed by
	 */
	public Collection<String> getWasInformedBy(String activity1Uri);
}
